### ISSUE TITLE
Do not store dataset in Client but pass as parameter

### ISSUE THREAD

**Issue by kvrhdn** [kvrhdn/go-honeycombio#2]
Not all requests are linked to a dataset, for instance when creating a board you can add queries that refer to multiple datasets. As such, it does not make sense to store a global dataset in `Client`.
We should change the APIs of marker and trigger to take a dataset parameter.

**Comment by fitzoh** [comment]
+1, feels a lot more natural if you want to create boards/triggers for multiple datasets.

Having to create `n` clients to interact with `n` environments feels weird.
